fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
france_connect:
    resource: App\Controller\FranceConnectController
    type:     annotation
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

blog:
    resource: App\Controller\Blog\BlogController
    type: annotation
    prefix: /actualites

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin_actualites
    type: annotation
ckfinder_connector:
    resource: "@CKSourceCKFinderBundle/Resources/config/routing.yml"
    prefix:   /
authentication_token:
    path: /authentication_token
    methods: ['POST']
